/* MEJORAS3.JS v8 */
(function(){"use strict";

function inyectarCSS(){if(document.getElementById("m4css"))return;var s=document.createElement("style");s.id="m4css";var css="";css+="#p-guardias .ptop,#p-guardias .ptitle{display:none!important}\n";css+="body:not(.m4tab-tablero) #p-tablero{display:none!important}\n";css+="body.m4tab-calendario #m1-pubs-guardias,body.m4tab-calendario .sidebar-pubs{display:none!important}\n";css+="#p-guardias .gwtbl{width:100%;overflow-x:auto}\n";css+="#p-guardias .gwb{display:flex;gap:6px;padding:8px}\n";css+="#p-guardias .gwd{flex:1;min-width:120px;background:var(--color-canvas-subtle,#f6f8fa);border:2px solid var(--color-border-default,#d0d7de);border-radius:10px;padding:8px;display:flex;flex-direction:column;gap:4px}\n";css+="#p-guardias .gwdate{font-weight:800;font-size:.9rem;color:#6c3fc5;text-align:center;padding-bottom:4px;border-bottom:1px solid var(--color-border-muted,#eaeef2);margin-bottom:4px}\n";css+="#p-guardias .gwag{display:flex;align-items:center;gap:4px;font-size:.78rem;padding:2px 0}\n";css+="#p-guardias .gwag>div:first-child{width:26px;height:26px;border-radius:50%;background:#6c3fc5;color:#fff;display:flex;align-items:center;justify-content:center;font-size:.6rem;font-weight:700;flex-shrink:0}\n";css+="#p-guardias .gwnb{border-radius:6px;padding:3px 7px;font-size:.72rem;border:1px solid var(--color-border-default,#d0d7de);background:var(--color-canvas-default,#fff);cursor:pointer;margin-top:2px;width:100%}\n";css+="#p-guardias .gwb .gwd>a{background:#25d366;color:#fff;border-radius:6px;padding:4px 8px;font-size:.72rem;font-weight:700;text-decoration:none;display:block;text-align:center;margin-top:2px}\n";css+="#p-guardias .gwh{display:none!important}\n";css+="#p-guardias .gwnb:first-of-type{background:#6c3fc5;color:#fff;border-color:#6c3fc5}\n";css+="#m4-hoy-cal{margin-top:12px;background:var(--color-canvas-subtle,#f6f8fa);border:1px solid #6c3fc5;border-radius:10px;padding:12px}\n";css+="#m4-hoy-cal .m4hdr{font-size:.85rem;font-weight:700;color:#6c3fc5;margin-bottom:8px}\n";css+="#m4-hoy-cal .m4hi{display:flex;align-items:flex-start;gap:8px;padding:5px 0;border-bottom:1px solid var(--color-border-muted,#eaeef2);font-size:.82rem}\n";css+="#m4-hoy-cal .m4hi:last-child{border-bottom:none}\n";css+="#m4-hoy-cal .m4ht{font-weight:800;color:#6c3fc5;min-width:44px}\n";css+=".m4-pub-del-btn{background:#ef4444;color:#fff;border:none;border-radius:5px;padding:3px 8px;font-size:.72rem;cursor:pointer;margin-left:6px;font-weight:600}\n";s.textContent=css;document.head.appendChild(s);}

function setTabClass(id){document.body.classList.toggle("m4tab-tablero",id==="tablero");document.body.classList.toggle("m4tab-calendario",id==="calendario"||id==="agenda-publicaciones"||id==="publicaciones");var t=document.querySelector("#p-tablero");if(t){if(id==="tablero")t.style.removeProperty("display");else t.style.setProperty("display","none","important");}}
function parchearNav(){var orig=window.nav;if(typeof orig!=="function"||window._m4navOK)return;window._m4navOK=true;window.nav=function(id){setTabClass(id);var r=orig.apply(this,arguments);if(id==="hoy")setTimeout(inyectarHoyCalendario,600);return r;};document.querySelectorAll(".ntab,.sbi").forEach(function(b){b.addEventListener("click",function(){var oc=this.getAttribute("onclick")||"";var dt=this.dataset.tab||"";var combined=oc+" "+dt;var id="other";if(combined.indexOf("tablero")>-1)id="tablero";else if(combined.indexOf("calendario")>-1)id="calendario";else if(combined.indexOf("publicaciones")>-1||combined.indexOf("agenda")>-1)id="agenda-publicaciones";else if(combined.indexOf("hoy")>-1)id="hoy";else if(combined.indexOf("guardias")>-1)id="guardias";setTabClass(id);},{capture:true});});}
function ocultarRealizada(){document.querySelectorAll(".kanban .kcol").forEach(function(col){var hdr=col.querySelector(".khdr .kt");if(!hdr)return;var lbl=(hdr.textContent||"").trim().replace(/[0-9]/g,"").trim();if(lbl==="Realizada"||lbl.indexOf("Realizada")===0)col.style.setProperty("display","none","important");});}
function fixScrollTablero(){var origRK=window.renderKanban;if(typeof origRK!=="function"||window._m4rkOK)return;window._m4rkOK=true;window.renderKanban=function(){var scrollPos={};document.querySelectorAll(".kanban .kcol .kcards").forEach(function(kc,i){scrollPos[i]=kc.scrollTop;});var kanban=document.querySelector(".kanban");var kanbanH=kanban?kanban.scrollLeft:0;var r=origRK.apply(this,arguments);requestAnimationFrame(function(){document.querySelectorAll(".kanban .kcol .kcards").forEach(function(kc,i){if(scrollPos[i])kc.scrollTop=scrollPos[i];});if(kanban&&kanbanH)kanban.scrollLeft=kanbanH;ocultarRealizada();});return r;};}

function inyectarHoyCalendario(){var old=document.getElementById("m4-hoy-cal");if(old)old.parentNode.removeChild(old);var phoy=document.getElementById("p-hoy");if(!phoy)return;var eventos=[];var todayStr=new Date().toISOString().substring(0,10);Object.keys(window).forEach(function(k){try{var v=window[k];if(!Array.isArray(v)||v.length<1)return;var f=v[0];if(!f||typeof f!=="object")return;if(!(f.summary||f.titulo||f.title))return;v.forEach(function(ev){var d=(ev.start&&(ev.start.date||ev.start.dateTime))||ev.fecha||ev.date||"";if(typeof d==="string"&&d.substring(0,10)===todayStr){var t=ev.start&&ev.start.dateTime?ev.start.dateTime.substring(11,16):"";var title=ev.summary||ev.titulo||ev.title||"";if(title)eventos.push({time:t,title:title});}});}catch(e){}});if(!eventos.length)return;var seen={};eventos=eventos.filter(function(e){var key=e.time+"|"+e.title;if(seen[key])return false;seen[key]=true;return true;});eventos.sort(function(a,b){return a.time.localeCompare(b.time);});var div=document.createElement("div");div.id="m4-hoy-cal";var h='<div class="m4hdr">&#128197; Eventos del calendario de hoy</div>';eventos.forEach(function(ev){h+='<div class="m4hi"><span class="m4ht">'+ev.time+'</span><span>'+ev.title+'</span></div>';});div.innerHTML=h;phoy.appendChild(div);}

function agregarBotonesEliminarPubs(){var pubCards=document.querySelectorAll(".pub-card,.pubcard,[class*=pub-card]");pubCards.forEach(function(card){if(card.querySelector(".m4-pub-del-btn"))return;var pubId=card.getAttribute("data-id")||card.id||"";var btn=document.createElement("button");btn.className="m4-pub-del-btn";btn.textContent="Eliminar";btn.onclick=function(e){e.stopPropagation();if(!confirm("Eliminar esta publicacion?"))return;if(typeof window.deletePub==="function")window.deletePub(pubId);else if(typeof window.borrarPub==="function")window.borrarPub(pubId);else if(typeof window._apBorrar==="function")window._apBorrar(pubId);else card.style.display="none";};var actions=card.querySelector(".pub-actions,.card-actions,[class*=actions],[class*=btns]");if(actions)actions.appendChild(btn);else card.appendChild(btn);});}
function init(){inyectarCSS();parchearNav();ocultarRealizada();fixScrollTablero();var activeTab="";document.querySelectorAll(".ntab.active,.sbi.active").forEach(function(el){var oc=el.getAttribute("onclick")||el.dataset.tab||"";if(oc.indexOf("tablero")>-1)activeTab="tablero";else if(oc.indexOf("calendario")>-1)activeTab="calendario";else if(oc.indexOf("publicaciones")>-1||oc.indexOf("agenda")>-1)activeTab="agenda-publicaciones";else if(oc.indexOf("hoy")>-1)activeTab="hoy";else if(oc.indexOf("guardias")>-1)activeTab="guardias";});setTabClass(activeTab);if(activeTab==="hoy")setTimeout(inyectarHoyCalendario,600);var debTimer=null;var obs=new MutationObserver(function(){clearTimeout(debTimer);debTimer=setTimeout(function(){ocultarRealizada();parchearNav();fixScrollTablero();agregarBotonesEliminarPubs();},400);});obs.observe(document.body,{childList:true,subtree:true,attributes:false});setInterval(function(){ocultarRealizada();parchearNav();fixScrollTablero();},3000);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);
else setTimeout(init,800);

})();
