/* MEJORAS3.JS v9 */
(function(){"use strict";
function inyectarCSS(){if(document.getElementById("m4css"))return;
var s=document.createElement("style");s.id="m4css";var css="";
css+="#p-guardias .gwtbl{display:none!important}\n";
css+="#p-guardias .ptop,#p-guardias .ptitle{display:none!important}\n";
css+="body:not(.m4tab-tablero) #p-tablero{display:none!important}\n";
css+="body.m4tab-calendario #m1-pubs-guardias{display:none!important}\n";
css+="#m4g{padding:0;font-family:inherit}\n";
css+="#m4g .m4g-header{background:linear-gradient(135deg,#6c3fc5,#8b5cf6);color:#fff;padding:14px 18px;border-radius:12px;margin-bottom:14px}\n";
css+="#m4g .m4g-header h2{margin:0;font-size:1.1rem;font-weight:800}\n";
css+="#m4g .m4g-nav{display:flex;align-items:center;gap:8px;margin-bottom:12px;flex-wrap:wrap}\n";
css+="#m4g .m4g-navbtn{background:#fff;border:1px solid #d0d7de;border-radius:8px;padding:6px 14px;cursor:pointer;font-size:.82rem;font-weight:600;color:#333}\n";
css+="#m4g .m4g-navbtn:hover{background:#f0f0f0}\n";
css+="#m4g .m4g-week{flex:1;text-align:center;font-weight:700;font-size:.95rem;color:#333}\n";
css+="#m4g .m4g-grid{display:flex;gap:8px;overflow-x:auto;padding-bottom:6px}\n";
css+="#m4g .m4g-card{flex:1;min-width:110px;background:#fff;border:2px solid #e2d8f7;border-radius:12px;padding:10px 8px;cursor:pointer;display:flex;flex-direction:column;align-items:center;gap:5px}\n";
css+="#m4g .m4g-card:hover{border-color:#6c3fc5}\n";
css+="#m4g .m4g-card.m4g-active{border-color:#6c3fc5;background:#f5f0ff}\n";
css+="#m4g .m4g-card.m4g-today{border-color:#f59e0b}\n";
css+="#m4g .m4g-cdate{font-size:.72rem;color:#888;font-weight:600;text-transform:uppercase;text-align:center}\n";
css+="#m4g .m4g-cday{font-size:1.3rem;font-weight:900;color:#6c3fc5;line-height:1}\n";
css+="#m4g .m4g-card.m4g-today .m4g-cday{color:#f59e0b}\n";
css+="#m4g .m4g-avatar{width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:.8rem;color:#fff;margin-top:3px}\n";
css+="#m4g .m4g-agname{font-size:.72rem;font-weight:700;text-align:center;color:#333;max-width:90px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n";
css+="#m4g .m4g-agrole{font-size:.64rem;color:#888;text-align:center}\n";
css+="#m4g .m4g-badge{background:#6c3fc5;color:#fff;border-radius:20px;padding:2px 9px;font-size:.68rem;font-weight:700;margin-top:3px}\n";
css+="#m4g .m4g-card.m4g-today .m4g-badge{background:#f59e0b}\n";
css+="#m4g .m4g-wa{display:block;background:#25d366;color:#fff;border-radius:7px;padding:4px 8px;font-size:.67rem;font-weight:700;text-decoration:none;text-align:center;width:100%;box-sizing:border-box;margin-top:3px}\n";
css+="#m4g .m4g-detail{display:flex;gap:14px;margin-top:14px;flex-wrap:wrap}\n";
css+="#m4g .m4g-main{flex:1;min-width:260px;background:#fff;border:1px solid #e2d8f7;border-radius:12px;padding:14px}\n";
css+="#m4g .m4g-side{width:200px;min-width:180px;display:flex;flex-direction:column;gap:10px}\n";
css+="#m4g .m4g-dheader{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;flex-wrap:wrap;gap:8px}\n";
css+="#m4g .m4g-dheader h3{margin:0;font-size:.95rem;font-weight:800;color:#6c3fc5}\n";
css+="#m4g .m4g-wa-big{background:#25d366;color:#fff;border:none;border-radius:8px;padding:7px 13px;font-size:.78rem;font-weight:700;text-decoration:none;display:inline-block}\n";
css+="#m4g .m4g-act{display:flex;align-items:flex-start;gap:10px;padding:8px 0;border-bottom:1px solid #f0eaf8}\n";
css+="#m4g .m4g-act:last-child{border-bottom:none}\n";
css+="#m4g .m4g-atime{font-weight:800;color:#6c3fc5;min-width:46px;font-size:.85rem}\n";
css+="#m4g .m4g-atype{display:inline-block;border-radius:5px;padding:1px 7px;font-size:.65rem;font-weight:700;color:#fff;white-space:nowrap;margin-bottom:2px}\n";
css+="#m4g .m4g-atype.cob{background:#6c3fc5}\n";
css+="#m4g .m4g-atype.cal{background:#2563eb}\n";
css+="#m4g .m4g-atype.pub{background:#f59e0b}\n";
css+="#m4g .m4g-atitle{font-size:.83rem;font-weight:600;color:#222}\n";
css+="#m4g .m4g-noact{text-align:center;color:#aaa;padding:24px 0;font-size:.85rem}\n";
css+="#m4g .m4g-resumen{background:#fff;border:1px solid #e2d8f7;border-radius:12px;padding:12px}\n";
css+="#m4g .m4g-resumen h4{margin:0 0 8px;font-size:.85rem;font-weight:800;color:#333}\n";
css+="#m4g .m4g-rrow{display:flex;justify-content:space-between;align-items:center;padding:4px 0;font-size:.8rem;border-bottom:1px solid #f5f5f5}\n";
css+="#m4g .m4g-rrow:last-child{border-bottom:none}\n";
css+="#m4g .m4g-rval{background:#6c3fc5;color:#fff;border-radius:12px;padding:1px 9px;font-size:.72rem;font-weight:700}\n";
css+="#m4g .m4g-agcard{background:#fff;border:1px solid #e2d8f7;border-radius:12px;padding:12px;display:flex;flex-direction:column;align-items:center;gap:5px}\n";
css+="#m4g .m4g-agcard .m4g-avatar{width:44px;height:44px;font-size:.95rem}\n";
css+="#m4g .m4g-agcard .m4g-agname{font-size:.88rem;font-weight:800;color:#333}\n";
css+="#m4g .m4g-agcard .m4g-agrole{font-size:.72rem;color:#888}\n";
s["textContent"]=css;document.head.appendChild(s);}
function instalarGCalInterceptor(){if(window._m4gcalOK)return;window._m4gcalOK=true;window._m4gcal=[];var _oF=window.fetch;window.fetch=function(){var args=arguments;var url=typeof args[0]==="string"?args[0]:((args[0]&&args[0].url)||"");var p=_oF.apply(this,args);if(url.indexOf("googleapis.com/calendar")>-1){p.then(function(res){var clone=res.clone();clone.json().then(function(data){if(data.items&&Array.isArray(data.items)){data.items.forEach(function(ev){window._m4gcal.push(ev);});if(window._m4renderPending){clearTimeout(window._m4renderTimer);window._m4renderTimer=setTimeout(function(){renderM4G();},500);}}}).catch(function(){});}).catch(function(){});}return p;};}
var _m4d=["DOM","LUN","MAR","MIE","JUE","VIE","SAB"];
var _m4m=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
var _m4ac=["#6c3fc5","#2563eb","#059669","#dc2626","#7c3aed","#db2777","#d97706","#0891b2","#65a30d","#9333ea"];
function _m4col(n){var h=0;for(var i=0;i<n.length;i++)h=(h*31+n.charCodeAt(i))%_m4ac.length;return _m4ac[Math.abs(h)];}
function extractDays(){var gwds=document.querySelectorAll(".gwtbl .gwd");var days=[];gwds.forEach(function(gwd){var dateEl=gwd.querySelector(".gwdate");var editBtn=gwd.querySelector(".gwnb");var oc=editBtn?(editBtn.getAttribute("onclick")||""):"";var dm=oc.match(new RegExp("'(\\d{4}-\\d{2}-\\d{2})'"));var iso=dm?dm[1]:"";var gwags=Array.from(gwd.querySelectorAll(".gwag"));var waLinks=Array.from(gwd.querySelectorAll("a"));var agents=gwags.map(function(ag,ai){var initEl=ag.querySelector("div");var sp=ag.querySelector("span");var rs=sp?sp.querySelector("span"):null;var name="";if(sp){var cl=sp.cloneNode(true);var rs2=cl.querySelector("span");if(rs2)rs2.remove();name=cl.textContent.trim();}var role=rs?rs.textContent.trim():"";var waHref=waLinks[ai]?waLinks[ai].href:"";return{initials:initEl?initEl.textContent.trim():"",name:name,role:role,waHref:waHref};});var acts=[];for(var ci=0;ci<gwd.children.length;ci++){var ch=gwd.children[ci];if(ch.textContent.indexOf("Coberturas del")>-1){for(var ai=1;ai<ch.children.length;ai++){var row=ch.children[ai];var td=row.children[1];if(td&&td.children.length>=2){var ti=td.children[0].textContent.trim();var tm=td.children[1].textContent.replace(/[^\d:]/g,"").trim();if(ti)acts.push({title:ti,time:tm,type:"cob"});}}break;}}days.push({isoDate:iso,dateText:dateEl?dateEl.textContent.trim():"",agents:agents,activities:acts});});return days;}
function getCalEvts(iso){if(!window._m4gcal||!iso)return[];var evs=[];var seen={};window._m4gcal.forEach(function(ev){var s=ev.start&&(ev.start.dateTime||ev.start.date)||"";if(s.substring(0,10)!==iso)return;var tm="00:00";if(ev.start&&ev.start.dateTime){var mm=ev.start.dateTime.match(/T(\d{2}:\d{2})/);if(mm)tm=mm[1];}var tl=ev.summary||"";if(!tl)return;var k=tm+"|"+tl;if(seen[k])return;seen[k]=true;evs.push({title:tl,time:tm,type:"cal"});});evs.sort(function(a,b){return a.time.localeCompare(b.time);});return evs;}
function getPubs(iso){var pubs=[];try{var raw=localStorage.getItem("panel-comunicacion-publicaciones-v1");if(raw){var all=JSON.parse(raw);if(Array.isArray(all)){all.forEach(function(p){var fd=p.fechaPublicacion||p.fecha||p.date||"";if(typeof fd==="string"&&fd.substring(0,10)===iso){var hora=(p.horaPublicacion||p.hora||p.time||"")+"";var title=p.texto||p.titulo||p.title||p.descripcion||"";if(title)pubs.push({title:title.substring(0,80),time:hora.substring(0,5),type:"pub"});}});}}}catch(e){}return pubs;}
var _m4sel=null;
function renderM4G(){var pg=document.getElementById("p-guardias");if(!pg)return;var days=extractDays();if(!days||days.length===0){window._m4renderPending=true;return;}window._m4renderPending=false;var navrow=document.querySelector(".gw-navrow.gw-desktop");var wkRange="";if(navrow){var sp=navrow.querySelector("span");wkRange=sp?sp.textContent.trim():"";}var todayISO=new Date().toISOString().substring(0,10);if(!_m4sel){var found=false;days.forEach(function(d){if(d.isoDate===todayISO&&!found){_m4sel=d.isoDate;found=true;}});if(!found&&days[0])_m4sel=days[0].isoDate;}var m4g=document.getElementById("m4g");if(!m4g){m4g=document.createElement("div");m4g.id="m4g";pg.appendChild(m4g);}var html="";
html+='<div class="m4g-header"><h2>&#128737; Guardias Semanales</h2></div>';
html+='<div class="m4g-nav"><button class="m4g-navbtn" onclick="if(window.goGuardWeek)goGuardWeek(-1);setTimeout(function(){_m4sel=null;renderM4G();},800)">&laquo; Ant</button><span class="m4g-week">'+(wkRange||"Esta semana")+'</span><button class="m4g-navbtn" onclick="if(window.goGuardWeek)goGuardWeek(1);setTimeout(function(){_m4sel=null;renderM4G();},800)">Sig &raquo;</button><button class="m4g-navbtn" onclick="if(window.goGuardWeek)goGuardWeek(0);setTimeout(function(){_m4sel=null;renderM4G();},800)">Hoy</button></div>';
html+='<div class="m4g-grid">';
days.forEach(function(d){if(!d.isoDate)return;var isToday=d.isoDate===todayISO;var isActive=d.isoDate===_m4sel;var dd=new Date(d.isoDate+"T12:00:00");var dayNum=dd.getDate();var dayName=_m4d[dd.getDay()]||"";var calEvs=getCalEvts(d.isoDate);var isWE=(dd.getDay()===0||dd.getDay()===6);var calF=calEvs.filter(function(e){return isWE||e.time>="15:00";});var total=d.activities.length+calF.length;var cls="m4g-card"+(isActive?" m4g-active":"")+(isToday?" m4g-today":"");var ag=d.agents[0]||{name:"Sin asignar",initials:"?",role:"",waHref:""};var bgC=_m4col(ag.name||"x");var inits=ag.initials||(ag.name?ag.name.substring(0,2).toUpperCase():"?");html+='<div class="'+(cls)+'" onclick="_m4sel=\"'+d.isoDate+'\";renderM4G()">';html+='<div class="m4g-cdate">'+dayName+'</div><div class="m4g-cday">'+dayNum+'</div>';html+='<div class="m4g-avatar" style="background:'+bgC+'">'+inits+'</div>';html+='<div class="m4g-agname">'+ag.name+'</div><div class="m4g-agrole">'+ag.role+'</div>';html+='<div class="m4g-badge">'+total+' act.</div>';if(ag.waHref)html+='<a class="m4g-wa" href="'+ag.waHref+'" target="_blank">&#128241; WhatsApp</a>';html+='</div>';});
html+='</div>';
var selDay=null;days.forEach(function(d){if(d.isoDate===_m4sel)selDay=d;});
if(selDay){var dd2=new Date(selDay.isoDate+"T12:00:00");var isWE2=(dd2.getDay()===0||dd2.getDay()===6);var tAg=selDay.agents[0]||{name:"Sin asignar",initials:"?",role:"titular",waHref:""};var detTitle=(_m4d[dd2.getDay()]||"")+" "+dd2.getDate()+" DE "+(_m4m[dd2.getMonth()]||"").toUpperCase()+" - "+tAg.name.toUpperCase()+" ("+tAg.role+")";var allActs=[];selDay.activities.forEach(function(a){allActs.push(a);});getCalEvts(selDay.isoDate).forEach(function(e){if(isWE2||e.time>="15:00")allActs.push(e);});getPubs(selDay.isoDate).forEach(function(p){if(isWE2||!p.time||p.time>="15:00")allActs.push(p);});allActs.sort(function(a,b){return(a.time||"00:00").localeCompare(b.time||"00:00");});var nCob=0,nCal=0,nPub=0;allActs.forEach(function(a){if(a.type==="cob")nCob++;else if(a.type==="cal")nCal++;else nPub++;});var waMsg="Hola "+tAg.name+", coberturas del d\u00eda\n"+(_m4d[dd2.getDay()]||"")+" "+dd2.getDate()+" de "+(_m4m[dd2.getMonth()]||"")+":\n\n";allActs.forEach(function(a){waMsg+=(a.time?a.time+" hs ":"")+a.title+"\n";});waMsg+="\n\uD83D\uDE4F Gracias!";var waUrl="https://api.whatsapp.com/send"+String.fromCharCode(63)+"text="+encodeURIComponent(waMsg);
html+='<div class="m4g-detail"><div class="m4g-main"><div class="m4g-dheader"><h3>'+detTitle+'</h3><a class="m4g-wa-big" href="'+waUrl+'" target="_blank">&#128241; Enviar cobertura</a></div>';
if(allActs.length===0){html+='<div class="m4g-noact">Sin actividades desde las 15:00 hs</div>';}else{allActs.forEach(function(act){var tL=act.type==="cob"?"COBERTURA":act.type==="cal"?"EVENTO":"PUBLICACI\u00d3N";html+='<div class="m4g-act"><div class="m4g-atime">'+(act.time||"")+'</div><div><div class="m4g-atype '+act.type+'">'+tL+'</div><div class="m4g-atitle">'+act.title+'</div></div></div>';});}
html+='</div><div class="m4g-side"><div class="m4g-resumen"><h4>Resumen del d\u00eda</h4>';
html+='<div class="m4g-rrow"><span>Total</span><span class="m4g-rval">'+allActs.length+'</span></div>';
html+='<div class="m4g-rrow"><span>Eventos</span><span class="m4g-rval">'+nCal+'</span></div>';
html+='<div class="m4g-rrow"><span>Publicaciones</span><span class="m4g-rval">'+nPub+'</span></div>';
html+='<div class="m4g-rrow"><span>Coberturas</span><span class="m4g-rval">'+nCob+'</span></div></div>';
html+='<div class="m4g-agcard"><div class="m4g-avatar" style="background:'+_m4col(tAg.name||"x")+'">'+( tAg.initials||(tAg.name?tAg.name.substring(0,2).toUpperCase():"?"))+'</div><div class="m4g-agname">'+tAg.name+'</div><div class="m4g-agrole">'+tAg.role+'</div>';
if(tAg.waHref)html+='<a class="m4g-wa" href="'+tAg.waHref+'" target="_blank">&#128241; WhatsApp</a>';
html+='</div></div></div>';}
m4g.innerHTML=html;}
function setTabClass(id){document.body.classList.toggle("m4tab-tablero",id==="tablero");document.body.classList.toggle("m4tab-calendario",id==="calendario"||id==="agenda-publicaciones"||id==="publicaciones");document.body.classList.toggle("m4tab-guardias",id==="guardias");var t=document.querySelector("#p-tablero");if(t){if(id==="tablero")t.style.removeProperty("display");else t.style.setProperty("display","none","important");}}
function parchearNav(){var orig=window.nav;if(typeof orig!=="function"||window._m4navOK)return;window._m4navOK=true;window.nav=function(id){setTabClass(id);var r=orig.apply(this,arguments);if(id==="guardias"){_m4sel=null;setTimeout(function(){renderM4G();},700);}if(id==="hoy")setTimeout(inyectarHoyCalendario,700);return r;};document.querySelectorAll(".ntab,.sbi").forEach(function(b){b.addEventListener("click",function(){var oc=this.getAttribute("onclick")||"";var dt=this.dataset.tab||"";var c=oc+" "+dt;var id="other";if(c.indexOf("tablero")>-1)id="tablero";else if(c.indexOf("calendario")>-1)id="calendario";else if(c.indexOf("publicaciones")>-1||c.indexOf("agenda")>-1)id="agenda-publicaciones";else if(c.indexOf("hoy")>-1)id="hoy";else if(c.indexOf("guardias")>-1)id="guardias";setTabClass(id);},{capture:true});});}
function ocultarRealizada(){document.querySelectorAll(".kanban .kcol").forEach(function(col){var hdr=col.querySelector(".khdr .kt");if(!hdr)return;var lbl=(hdr.textContent||"").trim().replace(/[0-9]/g,"").trim();if(lbl==="Realizada"||lbl.indexOf("Realizada")===0)col.style.setProperty("display","none","important");});}
function fixScrollTablero(){var origRK=window.renderKanban;if(typeof origRK!=="function"||window._m4rkOK)return;window._m4rkOK=true;window.renderKanban=function(){var sp={};document.querySelectorAll(".kanban .kcol .kcards").forEach(function(kc,i){sp[i]=kc.scrollTop;});var kb=document.querySelector(".kanban");var kbH=kb?kb.scrollLeft:0;var r=origRK.apply(this,arguments);requestAnimationFrame(function(){document.querySelectorAll(".kanban .kcol .kcards").forEach(function(kc,i){if(sp[i])kc.scrollTop=sp[i];});if(kb&&kbH)kb.scrollLeft=kbH;ocultarRealizada();});return r;};}
function inyectarHoyCalendario(){var old=document.getElementById("m4-hoy-cal");if(old)old.parentNode.removeChild(old);var phoy=document.getElementById("p-hoy");if(!phoy)return;var todayStr=new Date().toISOString().substring(0,10);var evts=getCalEvts(todayStr);if(!evts.length)return;var div=document.createElement("div");div.id="m4-hoy-cal";div.style.cssText="margin-top:12px;background:var(--color-canvas-subtle,#f6f8fa);border:1px solid #6c3fc5;border-radius:10px;padding:12px";var h='<div style="font-size:.85rem;font-weight:700;color:#6c3fc5;margin-bottom:8px">&#128197; Eventos del calendario de hoy</div>';evts.forEach(function(ev){h+='<div style="display:flex;gap:8px;padding:5px 0;border-bottom:1px solid #eaeef2;font-size:.82rem"><span style="font-weight:800;color:#6c3fc5;min-width:44px">'+ev.time+'</span><span>'+ev.title+'</span></div>';});div.innerHTML=h;phoy.appendChild(div);}
function init(){inyectarCSS();instalarGCalInterceptor();parchearNav();ocultarRealizada();fixScrollTablero();var activeTab="";document.querySelectorAll(".ntab.active,.sbi.active").forEach(function(el){var oc=el.getAttribute("onclick")||el.dataset.tab||"";if(oc.indexOf("tablero")>-1)activeTab="tablero";else if(oc.indexOf("calendario")>-1)activeTab="calendario";else if(oc.indexOf("publicaciones")>-1||oc.indexOf("agenda")>-1)activeTab="agenda-publicaciones";else if(oc.indexOf("hoy")>-1)activeTab="hoy";else if(oc.indexOf("guardias")>-1)activeTab="guardias";});setTabClass(activeTab);if(activeTab==="guardias"){window._m4renderPending=true;setTimeout(function(){renderM4G();},700);}if(activeTab==="hoy")setTimeout(inyectarHoyCalendario,700);if(typeof window.syncGCal==="function"&&!window._m4syncOK){window._m4syncOK=true;var origSync=window.syncGCal;window.syncGCal=function(){var r=origSync.apply(this,arguments);setTimeout(function(){if(document.body.classList.contains("m4tab-guardias"))renderM4G();var phoy=document.getElementById("p-hoy");if(phoy&&phoy.offsetParent)inyectarHoyCalendario();},1500);return r;};}var debTimer=null;var obs=new MutationObserver(function(){clearTimeout(debTimer);debTimer=setTimeout(function(){ocultarRealizada();parchearNav();fixScrollTablero();if(document.body.classList.contains("m4tab-guardias")){var gwtbl=document.querySelector(".gwtbl");if(gwtbl&&gwtbl.querySelectorAll(".gwd").length>0&&!document.getElementById("m4g"))renderM4G();}},400);});obs.observe(document.body,{childList:true,subtree:true,attributes:false});setInterval(function(){ocultarRealizada();parchearNav();fixScrollTablero();},3000);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);
else setTimeout(init,800);
})();
